### ISSUE TITLE
[Bug] ViaVersion Conflicts with this plugin

### ISSUE THREAD

**Issue by theplacer** [TreyRuffy/TreysDoubleJump#29]
When a player joins the server, the console spams this error:

`[22:50:33 ERROR]: Could not pass event PlayerJoinEvent to TreysDoubleJump v2.6.5
java.lang.NoSuchMethodError: us.myles.ViaVersion.api.Via.getManager()Lus/myles/ViaVersion/ViaManager;
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:347) ~[?:?]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:344) ~[?:?]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.viaversion.ViaFacet.findConnection(ViaFacet.java:96) ~[?:?]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.viaversion.ViaFacet.findProtocol(ViaFacet.java:100) ~[?:?]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:92) ~[?:?]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.facet.Facet.of(Facet.java:100) ~[?:?]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:109) ~[?:?]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:85) ~[?:?]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:89) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_282]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:88) ~[?:?]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
        at me.treyruffy.treysdoublejump.util.adventure.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]`

This bug can be reproduced by joining the server on any version/client.

There shouldn't be any errors and the player should be able to double jump perfectly fine.

**Version Information (please complete the following information):**
 - Paper
 - 1.8.9

**Comment by TreyRuffy** [comment]
I believe this is an issue with Adventure using the old ViaVersion API. What version of ViaVersion are you using? And are you using a 1.8.9 jar?

**Comment by theplacer** [comment]
Specifically, I'm using Paper 1.8.8. I upgraded to ViaVersion 4.0.0 today. I'm also connecting with Lunar 1.8.

**Comment by TreyRuffy** [comment]
Alright, I believe I fixed it with my latest commit. 71657e7dd8340a0ea4d1a8e22717590d6814830c

**Comment by TreyRuffy** [comment]
Can you check with https://github.com/TreyRuffy/TreysDoubleJump/releases/tag/2.6.6-PRE1

**Comment by theplacer** [comment]
It works now. Thank you!
