### ISSUE TITLE
Java 16 Update Broken

### ISSUE THREAD

**Issue by SladeHazard** [TreyRuffy/TreysDoubleJump#31]
Doesn't work on java 15

[07:32:42 ERROR]: Could not load 'plugins/TreysDoubleJump.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/treyruffy/treysdoublejump/TreysDoubleJump has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 59.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:317) ~[server.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:241) [server.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [server.jar:?]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:207) [server.jar:?]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [server.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.UnsupportedClassVersionError: me/treyruffy/treysdoublejump/TreysDoubleJump has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 59.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151) ~[?:?]
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:514) ~[?:?]
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:422) ~[?:?]
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:416) ~[?:?]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:415) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:103) ~[server.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:88) ~[server.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:66) ~[server.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:?]
        ... 6 more

**Comment by TreyRuffy** [comment]
Can you please redownload the newest version and try again. I believe I fixed it.

https://www.spigotmc.org/resources/treys-double-jump-api.19630/download?version=408827
